column_names:
- condition
- regio1
- regio2
- regio3
- yearConstructed
- livingSpace
- noRooms
condition_order:
- Other
- well_kept
- modernized
- refurbished
- fully_renovated
- mint_condition
- first_time_use
- first_time_use_after_refurbishment
one_hot_columns:
- regio1
- regio2
- regio3
one_hot_deleted:
- heatingType
- typeOfFlat
- newlyConst
- balcony
- hasKitchen
- lift
ordinal_columns:
- condition
standard_scaler_columns:
- yearConstructed
- livingSpace
- noRooms
target_column: totalRent
