language: en
column_names:
  - condition
  - regio2
  - hasKitchen
  - balcony
  - typeOfFlat
  - heatingType
  - newlyConst
  - livingSpace
  - noRooms
  - yearConstructed
condition_order:
  - Other
  - well_kept
  - modernized
  - refurbished
  - fully_renovated
  - mint_condition
  - first_time_use
  - first_time_use_after_refurbishment
one_hot_columns:
  - regio2
  - hasKitchen
  - balcony
  - typeOfFlat
  - heatingType
  - newlyConst
ordinal_columns:
  - condition
standard_scaler_columns:
  - livingSpace
  - noRooms
  - yearConstructed
target_column: totalRent
